gui:
  showFileTree: true
  showRandomTip: false
  sidePanelWidth: 0.25
  border: "single"
  showPanelJumps: false
  theme:
    lightTheme: false
    activeBorderColor:
      - "#5f8787"
      - bold
    inactiveBorderColor:
      - "#5f8787"
    optionsTextColor:
      - "#5f8787"
    selectedLineBgColor:
      - "#1a2c2e"
    cherryPickedCommitFgColor:
      - "#c9b98a"
    cherryPickedCommitBgColor:
      - "#1a2c2e"
    markedBaseCommitBgColor:
      - "#1a2c2e"
    markedBaseCommitFgColor:
      - "#c9b98a"
    unstagedChangesColor:
      - "#c9645a"
    defaultFgColor:
      - "#b0c4b0"
  nerdFontsVersion: "3"
  showBottomLine: false
  expandFocusedSidePanel: true
  authorColors:
    '*': '#b294bb'
git:
  autoFetch: true
  pagers:
    - pager: "delta --dark --paging=never --syntax-theme OneHalfDark -s --line-numbers --navigate --hyperlinks --file-style=\"bold yellow\" --hunk-header-style=\"line-number syntax\" --minus-style=\"syntax #3d0000\" --minus-emph-style=\"syntax #5f0000\" --plus-style=\"syntax #003d00\" --plus-emph-style=\"syntax #005f00\""
  commit:
    signOff: true
promptToReturnFromSubprocess: false

os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
